apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sideeye
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - configmap.yaml
  - pvc-efs.yaml
  - cronjob-chip.yaml
  - cronjob-ciam.yaml
