#!/usr/bin/env bash
# Collect system specs — paste output into .cursor/skills/forgeops-ciam-lab/SKILL.md metadata
set -euo pipefail

echo "=== System spec snapshot $(date -Iseconds) ==="
echo ""
echo "physical_host_os: Windows  # confirm manually if changed"
echo "dev_environment: Cursor cloud workspace (Docker container)"
echo "workspace_os: $(. /etc/os-release && echo "$PRETTY_NAME")"
echo "workspace_kernel: $(uname -r)"
echo "cpu_cores: $(nproc)"
echo "cpu_model: $(lscpu 2>/dev/null | grep 'Model name' | cut -d: -f2 | xargs || echo unknown)"
echo "ram_total_gib: $(free -g | awk '/Mem:/ {print $2}')"
echo "ram_available_gib: $(free -g | awk '/Mem:/ {print $7}')"
echo "swap: $(free -h | awk '/Swap:/ {print $2}')"
echo "disk_total_gib: $(df -BG / | awk 'NR==2 {print $2}' | tr -d G)"
echo "disk_free_gib: $(df -BG / | awk 'NR==2 {print $4}' | tr -d G)"
echo "virtualization: $(systemd-detect-virt 2>/dev/null || echo unknown)"
echo "cgroup_type: $(cat /sys/fs/cgroup/cgroup.type)"
echo "cgroup_subtree_control: $(cat /sys/fs/cgroup/cgroup.subtree_control 2>/dev/null || echo n/a)"
echo "cgroup_memory_delegated: $(cat /sys/fs/cgroup/cgroup.subtree_control 2>/dev/null | grep -q memory && echo true || echo false)"
echo "docker_version: $(docker --version 2>/dev/null | awk '{print $3}' | tr -d , || echo not-installed)"
echo "docker_storage_driver: $(docker info 2>/dev/null | grep 'Storage Driver' | awk '{print $3}' || echo n/a)"
echo "node_version: $(node --version 2>/dev/null || echo not-installed)"
echo "python_version: $(python3 --version 2>/dev/null | awk '{print $2}' || echo not-installed)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "forgeops_runnable_in_workspace: $("$SCRIPT_DIR/check-cgroup.sh" >/dev/null 2>&1 && echo true || echo false)"
echo ""
echo "Run ./forgeops/scripts/check-cgroup.sh for full deployment guidance."
